name: install apt packages
description: install apt packages
runs:
  using: "composite"
  steps:
    - name: install apt packages
      shell: bash
      run: sudo apt-get install -y libsodium-dev protobuf-compiler
