name: try and merge the current branch with another branch
description: try and merge the current branch with another branch
inputs:
  merge_into:
    description: "The operating system to use"
    required: true
    default: "next"

  git_user:
    description: "paths to cache"
    required: false
    default: "Github Actions"

  git_email:
    description: "mix environment to use"
    required: false
    default: "nobody@localhost"

runs:
  using: "composite"
  steps:
    # checkout the repo with depth 0 to get all the branches.
    - name: Check out the repository to the runner
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0

    # get the current commit hash and store in the environment under `$SHA`
    - name: get the current commit hash 
      id: commit_hash
      shell: bash 
      run: echo "SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

    # checkout the target branch
    - name: checkout the target branch 
      shell: bash
      run: git checkout ${{ inputs.merge_into }}

    # try and merge the commit into the target branch
    - name: merge the commit into the checked out branch 
      shell: bash
      run: git -c user.name="${{ inputs.git_user }}" -c user.email="${{ inputs.git_email }}" merge $SHA
