name: try and merge the current branch with another branch
description: try and merge the current branch with another branch
inputs:
  merge_into:
    description: "The operating system to use"
    required: true
    default: "next"

  merge_commit:
    description: "mix environment to use"
    required: true

  git_user:
    description: "paths to cache"
    required: false
    default: "Github Actions"

  git_email:
    description: "mix environment to use"
    required: false
    default: "nobody@localhost"

runs:
  using: "composite"
  steps:
    # get the current commit hash 
    - name: get the current commit hash 
      id: commit_hash
      shell: bash 
      run: echo "::set-output name=commit_hash::$(git rev-parse HEAD)"

    - name: echo the current commit hash 
      shell: bash 
      run: echo ${{ steps.commit_hash.outputs.commit_hash }}
    # checkout the target branch
    # - name: checkout the target branch 
    #   shell: bash
    #   run: git checkout ${{ inputs.merge_into }}

    # # try and merge the commit into the target branch
    # - name: merge the commit into the checked out branch 
    #   shell: bash
    #   run: git -c user.name="${{ inputs.git_user }}" -c user.email="${{ inputs.git_email }}" merge ${{ inputs.merge_commit }}
