name: try and merge the current branch with another branch
description: try and merge the current branch with another branch
inputs:
  merge_into:
    description: "The operating system to use"
    required: true
    default: "next"

  merge_commit:
    description: "mix environment to use"
    required: true

  git_user:
    description: "paths to cache"
    required: false
    default: "Github Actions"

  git_email:
    description: "mix environment to use"
    required: false
    default: "nobody@localhost"

runs:
  using: "composite"
  steps:
    - run: git checkout ${{ inputs.merge_into }}
    - run: git -c user.name="${{ inputs.git_user }}" -c user.email="${{ inputs.git_email }}" merge ${{ inputs.merge_commit }}
