name: setup build cache
description: setup the build cache for the mix environment
inputs:
  mix_env:
    description: mix env
    required: true
    type: string
  paths:
    description: paths to cache
    required: true
    type: string
  os:
    description: os of the runner
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: use build cache
      uses: actions/cache@v4
      with:
        key: ${{ inputs.os }}-build-${{ inputs.mix_env }}-${{ hashFiles('**/mix.lock') }}
        path: |
          ${{ inputs.paths }}
