name: compile the documentation
description: compile the documentation
runs:
  using: "composite"
  steps:
    # install os deps
    - uses: ./.github/workflows/subtasks/os_dependencies

    # install erlang/elixir/protobuf
    - uses: ./.github/workflows/subtasks/elixir_setup

    # setup build cache
    - uses: ./.github/workflows/subtasks/cache
      with:
        os: ${{ runner.os }}
        mix_env: ${{ inputs.mix_env }}
        paths: |
          ${{ github.workspace }}/deps
          ${{ github.workspace }}/_build

    # run mix credo
    - name: "compile docs"
      shell: bash
      run: make docs-release
