name: create a release on GitHub and publish the binaries
description: create a release on GitHub and publish the binaries
inputs:
  release_name:
    description: "The name of the release"
    required: true
  github_token:
    description: "The github token"
    required: true

runs:
  using: "composite"
  steps:
    #---------------------------------------------------------------------------
    # Create the release on GitHub, or fail if it exists.
    - name: ensure that the release does not exist yet
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      shell: bash
      run: |
        export RELEASE=$(gh release list --json name | jq '.[] | select(.name == "${{ inputs.release_name }}") | .name') ; \
        test -z "${RELEASE}" || echo "release ${RELEASE} already exists"

    - name: create the release on github
      continue-on-error: true
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      shell: bash
      run: |
        gh release create ${{ inputs.release_name }} \
          --title ${{ github.ref_name }}             \
          --repo ${{ github.repository }}

    #---------------------------------------------------------------------------
    # Publish releases

    - name: publish client release
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        gh release upload ${{ inputs.release_name }} \
        -- clobber                                   \
        apps/anoma_client/anoma_client