name: build the release binaries
description: build the release binaries
runs:
  using: "composite"
  steps:
    #---------------------------------------------------------------------------
    # Anoma Client binary

    - name: build the anoma client release
      shell: bash
      run: |
        MIX_ENV=prod mix do --app anoma_client escript.build