name: compile all elixir environments
description: compile all elixir environments
inputs:
  os:
    description: "The operating system to use"
    required: true

  paths:
    description: "paths to cache"
    required: true

  mix_env:
    description: "mix environment to use"
    required: true

runs:
  using: "composite"
  steps:
    # install os deps
    - uses: ./.github/workflows/subtasks/os_dependencies

    # install erlang/elixir/protobuf
    - uses: ./.github/workflows/subtasks/elixir_setup

    # setup build cache
    - uses: ./.github/workflows/subtasks/cache
      with:
        os: ${{ runner.os }}
        mix_env: ${{ inputs.mix_env }}
        paths: |
          ${{ github.workspace }}/deps
          ${{ github.workspace }}/_build

    - name: fetch deps
      shell: bash
      run: MIX_ENV=${{inputs.mix_env}} mix deps.get --only ${{inputs.mix_env}}

    - name: compile
      shell: bash
      run: MIX_ENV=${{inputs.mix_env}} mix compile --warnings-as-errors
