name: build and publish releases on github
description: build and publish releases on github
runs:
  using: "composite"
  steps:
    # install os deps
    - uses: ./.github/workflows/subtasks/os_dependencies

    # install erlang/elixir/protobuf
    - uses: ./.github/workflows/subtasks/elixir_setup

    # setup build cache
    - uses: ./.github/workflows/subtasks/cache
      with:
        os: ${{ runner.os }}
        mix_env: ${{ inputs.mix_env }}
        paths: |
          ${{ github.workspace }}/deps
          ${{ github.workspace }}/_build

      # build the release binaries
      - uses: ./.github/workflows/subtasks/build_release

      # build the release binaries
      - uses: ./.github/workflows/subtasks/github_release
        with:
          release_name: ${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
