name: Compile workflow

on:
  workflow_call:
    inputs:
      mix-env:
        required: true
        type: string
    secrets:
      token:
        required: false

jobs:
  cache: 
    runs-on: ubuntu-latest 
    steps:
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        key: foo 
        paths: ${{ github.workspace }}/deps
        
  compile:
    runs-on: ubuntu-latest
    steps:
    - 
    - name: compile
      shell: bash 
      run: echo "yeet"
