name: Compile, test, lint, and deploy

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

#-------------------------------------------------------------------------------
jobs:
  compile:
    name: compile code
    strategy:
      matrix:
        mix_env: ["prod", "dev", "test"]
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      # install deps
      - uses: ./.github/workflows/os_dependencies

      # setup build cache
      - uses: ./.github/workflows/cache
        with:
          os: ${{ runner.os }}
          mix_env: ${{ matrix.mix_env }}
          paths: |
            ${{ github.workspace }}/deps 
            ${{ github.workspace }}/_build

      # fetch deps and compile
      - run: MIX_ENV=${{matrix.mix_env}} mix deps.get --only ${{matrix.mix_env}}

      - run: MIX_ENV=${{matrix.mix_env}} mix compile --warnings-as-errors

  lint:
    needs: [compile]
    name: lint codebase
    strategy:
      matrix:
        mix_env: ["dev"]
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      # install deps
      - uses: ./.github/workflows/os_dependencies

      # setup build cache
      - uses: ./.github/workflows/cache
        with:
          os: ${{ runner.os }}
          mix_env: ${{ matrix.mix_env }}
          paths: |
            ${{ github.workspace }}/deps 
            ${{ github.workspace }}/_build

      # run mix credo
      - run: MIX_ENV=${{matrix.mix_env}} mix credo

      # check formatting
      - run: MIX_ENV=${{matrix.mix_env}} mix format --check-formatted

      # dialyzer 
      - run: MIX_ENV=${{matrix.mix_env}} mix dialyzer

  test:
    needs: [compile]
    name: run tests
    strategy:
      matrix:
        mix_env: ["test"]
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      # install deps
      - uses: ./.github/workflows/os_dependencies

      # setup build cache
      - uses: ./.github/workflows/cache
        with:
          os: ${{ runner.os }}
          mix_env: ${{ matrix.mix_env }}
          paths: |
            ${{ github.workspace }}/deps 
            ${{ github.workspace }}/_builds

      # run mix test
      - run: MIX_ENV=${{matrix.mix_env}} mix test

  docs:
    needs: [compile]
    name: generate documentation
    strategy:
      matrix:
        mix_env: ["dev"]
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      # install deps
      - uses: ./.github/workflows/os_dependencies

      # setup build cache
      - uses: ./.github/workflows/cache
        with:
          os: ${{ runner.os }}
          mix_env: ${{ matrix.mix_env }}
          paths: |
            ${{ github.workspace }}/deps 
            ${{ github.workspace }}/_builds


      # run mix docs
      - run: MIX_ENV=${{matrix.mix_env}} mix docs
