name: Compile, test, lint, and deploy

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

#-------------------------------------------------------------------------------
jobs:
  compile:
    name: compile code
    strategy:
      matrix:
        mix_env: ["prod", "dev", "test"]
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      # install deps 
      - uses: ./.github/workflows/os_dependencies 
      # setup build cache
      - uses: ./.github/workflows/cache
        with:
          os: ${{ runner.os }}
          mix_env: ${{ matrix.mix_env }}
          paths: |
            ${{ github.workspace }}/deps 
            ${{ github.workspace }}/_build
      # # setup the build cache
      # - name: use build cache
      #   uses: actions/cache@v4
      #   with:
      #     key: ${{ runner.os }}-build-${{ matrix.mix_env }}-${{ hashFiles('**/mix.lock') }}
      #     path: |
      #       ${{ github.workspace }}/deps 
      #       ${{ github.workspace }}/_build

      # # setup the beam
      # - name: configure beam
      #   uses: erlef/setup-beam@v1
      #   with:
      #     otp-version: "27.1"
      #     elixir-version: "1.17"

      # # fetch deps and compile
      # - run: MIX_ENV=${{matrix.mix_env}} mix deps.get --only ${{matrix.mix_env}}

      # - run: MIX_ENV=${{matrix.mix_env}} mix compile --warnings-as-errors

  # lint:
  #   needs: [compile]
  #   name: lint codebase
  #   strategy:
  #     matrix:
  #       mix_env: ["dev"]
  #   runs-on: ubuntu-latest
  #   steps:
  #     # checkout the repo
  #     - name: Check out the repository to the runner
  #       uses: actions/checkout@v4

  #     # setup the build cache
  #     - name: use build cache
  #       uses: actions/cache@v4
  #       with:
  #         key: ${{ runner.os }}-build-${{ matrix.mix_env }}-${{ hashFiles('**/mix.lock') }}
  #         path: |
  #           ${{ github.workspace }}/deps 
  #           ${{ github.workspace }}/_build

  #     # setup the beam
  #     - name: configure beam
  #       uses: erlef/setup-beam@v1
  #       with:
  #         otp-version: "27.1"
  #         elixir-version: "1.17"

  #     # run mix credo 
  #     - run: MIX_ENV=${{matrix.mix_env}} mix credo 

  #     # check formatting
  #     - run: MIX_ENV=${{matrix.mix_env}} mix format --check-formatted

  # test:
  #   needs: [compile]
  #   name: run tests
  #   strategy:
  #     matrix:
  #       mix_env: ["test"]
  #   runs-on: ubuntu-latest
  #   steps:
  #     # checkout the repo
  #     - name: Check out the repository to the runner
  #       uses: actions/checkout@v4

  #     # setup the build cache
  #     - name: use build cache
  #       uses: actions/cache@v4
  #       with:
  #         key: ${{ runner.os }}-build-${{ matrix.mix_env }}-${{ hashFiles('**/mix.lock') }}
  #         path: |
  #           ${{ github.workspace }}/deps 
  #           ${{ github.workspace }}/_build

  #     # setup the beam
  #     - name: configure beam
  #       uses: erlef/setup-beam@v1
  #       with:
  #         otp-version: "27.1"
  #         elixir-version: "1.17"

  #     # run mix credo 
  #     - run: MIX_ENV=${{matrix.mix_env}} mix test

  # docs:
  #   needs: [compile]
  #   name: generate documentation
  #   strategy:
  #     matrix:
  #       mix_env: ["prod"]
  #   runs-on: ubuntu-latest
  #   steps:
  #     # checkout the repo
  #     - name: Check out the repository to the runner
  #       uses: actions/checkout@v4

  #     # setup the build cache
  #     - name: use build cache
  #       uses: actions/cache@v4
  #       with:
  #         key: ${{ runner.os }}-build-${{ matrix.mix_env }}-${{ hashFiles('**/mix.lock') }}
  #         path: |
  #           ${{ github.workspace }}/deps 
  #           ${{ github.workspace }}/_build

  #     # setup the beam
  #     - name: configure beam
  #       uses: erlef/setup-beam@v1
  #       with:
  #         otp-version: "27.1"
  #         elixir-version: "1.17"

  #     # run mix credo 
  #     - run: MIX_ENV=${{matrix.mix_env}} mix docs