# This action runs on the code base for every new pull request that is goig to be merged into base.

# The action is divided into four jobs:

#   - Compile the deps and program for the different mix environments.
#   - Run linting jobs on the code base (credo, formatting, dialyzer, and whitespace check).
#   - Run the test suite against the code base.

name: Push

run-name: Push



on: [push]

jobs:
  compile:
    uses: ./.github/workflows/compile.yaml
    with:
      mix-env: "dev"
