name: Push

run-name: Push

on: [push]

jobs:
  compile:
    strategy:
      matrix:
        target: [dev, test, prod]
    uses: anoma/anoma/.github/compile.yaml
    with:
      mix-env: ${{ matrix.target }}
