name: Push

run-name: Push

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [dev, test, prod]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/compile
