name: Push
run-name: Push
on: [push]
env:
  OTP_VERSION: "1.17"
  ELIXIR_VERSION: "27.1"
jobs:
  try_merge:
    name: Try Merge with main
    uses: ./.github/workflows/try_merge.yaml
    with:
      merge_with: "main"

  compile:
    strategy:
      matrix:
        target: [dev, test, prod]
    name: "Compile ${{ matrix.target }}"
    uses: ./.github/workflows/compile.yaml
    with:
      mix-env: ${{ matrix.target }}
      elixir-version: "1.17"
      otp-version: "27.1"

  lint:
    needs: compile
    name: "Lint"
    uses: ./.github/workflows/lint.yaml
    with:
      mix-env: "dev"
      elixir-version: "1.17"
      otp-version: "27.1"

  test:
    needs: compile
    name: Test
    uses: ./.github/workflows/test.yaml
    with:
      mix-env: "test"
      elixir-version: "1.17"
      otp-version: "27.1"

  docs:
    needs: compile
    name: Generate docs
    uses: ./.github/workflows/docs.yaml
    with:
      mix-env: "test"
      elixir-version: "1.17"
      otp-version: "27.1"
