name: Push
run-name: Push
on: [push]
env:
  OTP_VERSION: "1.17"
  ELIXIR_VERSION: "27.1"
jobs:
  try_merge:
    uses: ./.github/workflows/try_merge.yaml
    with:
      merge_with: "main"

  compile:
    strategy:
      matrix:
        target: [dev, test, prod]
    uses: ./.github/workflows/compile.yaml
    with:
      mix-env: ${{ matrix.target }}
      elixir-version: "1.17"
      otp-version: "27.1"

  lint:
    needs: compile
    uses: ./.github/workflows/lint.yaml
    with:
      mix-env: "dev"
      elixir-version: "1.17"
      otp-version: "27.1"

  test:
    needs: compile
    uses: ./.github/workflows/test.yaml
    with:
      mix-env: "test"
      elixir-version: "1.17"
      otp-version: "27.1"

  docs:
    needs: compile
    permissions:
      contents: write
      id-token: write
      pages: write
    uses: ./.github/workflows/docs.yaml
    with:
      mix-env: "dev"
      elixir-version: "1.17"
      otp-version: "27.1"

  make_release:
    needs: [compile, lint, test, docs, try_merge]
    permissions:
      contents: write
      id-token: write
      pages: write
    uses: ./.github/workflows/build_release.yaml
    with:
      mix-env: "prod"
      elixir-version: "1.17"
      otp-version: "27.1"
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
