name: Push

run-name: Push

on: [push]

env:
  OTP_VERSION: "1.17"
  ELIXIR_VERSION: "27.1"
jobs:
  compile:
    strategy:
      matrix:
        target: [dev, test, prod]
    uses: ./.github/workflows/compile.yaml
    with:
      mix-env: ${{ matrix.target }}
      elixir-version: "1.17"
      otp-version: "27.1"
  lint:
    needs: compile
    uses: ./.github/workflows/lint.yaml
    with:
      mix-env: "dev"
      elixir-version: "1.17"
      otp-version: "27.1"

