name: Push

run-name: Push

on: [push]

jobs:
  compile:
    strategy:
      matrix:
        target: [dev, test, prod]
    uses: ./.github/compile.yaml@${{ github.ref_name }}
    with:
      mix-env: ${{ matrix.target }}
