# This action runs on the code base for every new pull request that is goig to be merged into base.

# The action is divided into four jobs:

#   - Compile the deps and program for the different mix environments.
#   - Run linting jobs on the code base (credo, formatting, dialyzer, and whitespace check).
#   - Run the test suite against the code base.

name: Push

run-name: Push to ${{ github.ref_name }}

on: [push]

jobs:
  # #-----------------------------------------------------------------------------
  # # Merge the current branch into the `next` branch.
  
  # try_merge:
  #   name: try merge into next
  #   runs-on: ubuntu-latest
  #   steps:
  #     # checkout the repo
  #     - name: Check out the repository to the runner
  #       uses: actions/checkout@v4

  #     # try merge with next
  #     - uses: ./.github/workflows/tasks/try_merge
  #       with:
  #         merge_into: "main"
  

  #-----------------------------------------------------------------------------
  # Compile the code base for the different mix environments
  # and cache the output of the _build and deps directories.

  compile:
    name: compile code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mix_env: ["prod", "dev", "test"]
    steps:
      # checkout the repo
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      # compile the code for all mix environments
      - uses: ./.github/workflows/tasks/compile
        with:
          mix_env: ${{ matrix.mix_env }}

  # #-----------------------------------------------------------------------------
  # # Run linting jobs on the code base.
  # # This includes credo, formatting, trailing whitespaces, and dialyzer.
  # # Reuses the cache from above, and updates the cache when the job is done.

  # lint:
  #   needs: [compile]
  #   name: lint codebase
  #   runs-on: ubuntu-latest
  #   steps:
  #     # checkout the repo
  #     - name: Check out the repository to the runner
  #       uses: actions/checkout@v4

  #     # run the lint jobs
  #     - uses: ./.github/workflows/tasks/lint
  #       with:
  #         mix_env: "dev"

  # #-----------------------------------------------------------------------------
  # # Run the test suite against the code base.

  # test:
  #   needs: [compile]
  #   name: run tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     # checkout the repo
  #     - name: Check out the repository to the runner
  #       uses: actions/checkout@v4

  #     # run the lint jobs
  #     - uses: ./.github/workflows/tasks/test

  # #-----------------------------------------------------------------------------
  # # Generate the documentation of the code base.

  # docs:
  #   needs: [compile]
  #   name: compile docs
  #   runs-on: ubuntu-latest
  #   steps:
  #     # checkout the repo
  #     - name: Check out the repository to the runner
  #       uses: actions/checkout@v4

  #     # run the lint jobs
  #     - uses: ./.github/workflows/tasks/docs

  # #-----------------------------------------------------------------------------
  # # Generate the documentation of the code base.

  # publish_docs:
  #   needs: [compile]
  #   name: publish docs
  #   runs-on: ubuntu-latest
  #   steps:
  #     # checkout the repo
  #     - name: Check out the repository to the runner
  #       uses: actions/checkout@v4

  #     # run the lint jobs
  #     - uses: ./.github/workflows/tasks/publish_docs